#FROM balenalib/raspberrypi3-python
FROM arm32v7/python:3.6-slim-stretch

MAINTAINER Vithar Me <vithar@vithar.me>

RUN apt-get update && apt-get upgrade -y && apt-get install build-essential cmake gfortran git wget -y
RUN apt-get install -y --fix-missing \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-dev \
    libavcodec-dev \
    libavformat-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    python3-numpy \
    software-properties-common \
    zip \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*
RUN apt-get install -y libopenblas-dev liblapack-dev libatlas-base-dev libx11-dev libgtk-3-dev python-pip python-dev build-essential
RUN pip2 install dlib
#RUN mkvirtualenv dlib_test -p python
#RUN workon cv && pip install numpy && pip install dlib
#RUN cd ~ && \
#    mkdir -p dlib && \
#    git clone -b 'v19.9' --single-branch https://github.com/davisking/dlib.git dlib/ && \
#    cd  dlib/ && \
#    python setup.py install --yes USE_AVX_INSTRUCTIONS
#RUN cd ~ && \
#    git clone https://github.com/ageitgey/face_recognition && \
#    cd face_recognition && \
#    pip3 install -r requirements.txt && \
#    python3 setup.py install
#CMD cd /root/face_recognition/examples && \
#    python3 recognize_faces_in_pictures.py
RUN cd ~ && git clone https://github.com/VitharMe/faceswap
RUN cd ~/faceswap && \
    wget http://sourceforge.net/projects/dclib/files/dlib/v18.10/shape_predictor_68_face_landmarks.dat.bz2 && \
    bzip2 -d shape_predictor_68_face_landmarks.dat.bz2
RUN apt-get install -y python-opencv
COPY move.sh /root/.
RUN chmod +x /root/move.sh
#RUN apt-get install python-opencv python-scipy ipython -y
#RUN apt-get install python-dlib
CMD ["/root/move.sh"]
